name : terraform run

on:
  workflow_dispatch:

jobs: 
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}         # Load AWS Access Key from GitHub Secrets
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init
      
      - name: terraform plan
        run: terraform plan -out=tfplan

      - name: terraform apply
        run: terraform apply --auto-approve tfplan 


